import NavbarContainer from "@/components/layout/navbar/NavbarContainer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={inter.className}
        style={{
          minHeight: "calc(100vh - 250px)",
          overflowX: "hidden",
          backgroundColor: "rgb(26, 29, 41)",
          transition: "opacity 200ms ease 0s",
        }}
      >
        <NavbarContainer />
        {children}
      </body>
    </html>
  );
}
