import NavbarContainer from "@/components/layout/navbar/NavbarContainer";
import "./globals.css";
import { Inter } from "next/font/google";
import ProviderStore from "@/store/ProviderStore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={inter.className}
        style={{
          minHeight: "100vh",
          overflowX: "hidden",
          background: "url(https://res.cloudinary.com/dishtratk/image/upload/v1687204209/disney-app/common/background_qwilef.png)",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          transition: "opacity 200ms ease 0s",
        }}
      >
        <ProviderStore>
          <NavbarContainer />
          {children}
        </ProviderStore>
      </body>
    </html>
  );
}
